compile_pdf:
  image: tianon/latex
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    {%- if cookiecutter.type == "tex" -%}
    - latexmk -pdf {{cookiecutter.directory_name}}.tex
    {%- elif cookiecutter.type == "md" -%}
    - pandoc -t beamer --template=lhcb.beamer {{cookiecutter.file_name}}.md -o  {{cookiecutter.file_name}}.pdf
    {%- endif -%}
  artifacts:
    paths:
      - {{cookiecutter.file_name}}.pdf

